import React, { useState, useEffect } from "react";
import { 
  BarChart3, 
  TrendingUp, 
  Users, 
  BookOpen, 
  Award, 
  CheckCircle2, 
  Clock, 
  Building2, 
  Download, 
  Filter, 
  Layers, 
  ShieldCheck, 
  Sparkles, 
  AlertCircle,
  HelpCircle,
  Activity,
  UserCheck,
  GraduationCap,
  Calendar,
  ChevronRight,
  PieChart as PieIcon
} from "lucide-react";
import { api } from "../../services/api";

export const PlatformAnalyticsView = () => {
  const [activeSubTab, setActiveSubTab] = useState("capacity"); // "capacity" | "performance" | "faculty" | "compliance"
  const [timeRange, setTimeRange] = useState("FY 2025-26");
  const [stats, setStats] = useState(null);
  const [courses, setCourses] = useState([]);
  const [trainersWorkload, setTrainersWorkload] = useState([]);
  const [quizzes, setQuizzes] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadAnalyticsData();
  }, []);

  const loadAnalyticsData = async () => {
    setLoading(true);
    try {
      const [statsRes, coursesRes, workloadRes, quizRes] = await Promise.all([
        api.getAdminStats().catch(() => ({ success: false })),
        api.getCourses().catch(() => ({ success: false })),
        api.getTrainersWorkload().catch(() => ({ success: false })),
        api.getQuizzes().catch(() => ({ success: false }))
      ]);

      if (statsRes.success) setStats(statsRes.stats);
      if (coursesRes.success) setCourses(coursesRes.courses || []);
      if (workloadRes.success) setTrainersWorkload(workloadRes.workload || []);
      if (quizRes.success) setQuizzes(quizRes.quizzes || []);
    } catch (err) {
      console.error("Failed to load platform analytics:", err);
    } finally {
      setLoading(false);
    }
  };

  // Compute live capacity statistics
  const totalEnrolled = courses.reduce((acc, c) => acc + (c.enrolledTraineeIds?.length || 0), 0);
  const totalMaxCapacity = courses.reduce((acc, c) => acc + (c.maxEnrollment || 50), 0);
  const capacityUtilizationPct = totalMaxCapacity > 0 ? Math.round((totalEnrolled / totalMaxCapacity) * 100) : 0;

  const handleExportReport = () => {
    const reportText = `=====================================================
NATIONAL CAPACITY BUILDING PLATFORM ANALYTICS REPORT
Generated On: ${new Date().toLocaleString()}
Time Horizon: ${timeRange}
=====================================================

1. EXECUTIVE SUMMARY:
- Total Standardized Courses: ${courses.length}
- Total Enrolled Officer Trainees: ${totalEnrolled}
- Platform Maximum Seat Capacity: ${totalMaxCapacity}
- Overall Capacity Utilization: ${capacityUtilizationPct}%
- Overall Assessment Pass Rate: ${stats?.overallPassRate || 0}%
- Total Certified Credentials Issued: ${stats?.totalCertificatesIssued || 0}

2. PROGRAM-WISE ENROLLMENT BREAKDOWN:
${courses.map(c => `* [${c.code}] ${c.title} -> ${c.enrolledTraineeIds?.length || 0}/${c.maxEnrollment || 50} Enrolled (${c.category})`).join("\n")}

3. FACULTY WORKLOAD DISTRIBUTION:
${trainersWorkload.map(t => `* ${t.trainerName} (${t.designation || 'Faculty'}) -> Active Courses: ${t.activeCoursesCount}, Subjects: ${t.assignedSubjects?.length || 0}, Status: ${t.status}`).join("\n")}

Report officially verified and generated by Capacity Connect Administrative Services.`;

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `MoES_Platform_Analytics_Report_${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      
      {/* ─── HEADER BANNER (CLEAN LIGHT THEME) ─── */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 text-slate-800 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-6 border border-slate-200/90 relative overflow-hidden">
        <div className="space-y-1.5 max-w-2xl z-10">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full bg-blue-50 border border-blue-200 text-[#0a2558] text-[10px] font-black uppercase tracking-wider">
              MoES Governance & MIS Analytics
            </span>
            <span className="text-xs text-slate-400 font-medium">• Real-Time National Training Telemetry</span>
          </div>
          <h1 className="text-xl sm:text-2xl font-black tracking-tight text-slate-900 flex items-center gap-2.5">
            <BarChart3 className="w-6 h-6 text-blue-700" />
            National LMS Platform Analytics & Reporting
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 font-medium leading-relaxed">
            Monitor training pipeline utilization, competency evaluations, class performance distributions, and faculty teaching loads.
          </p>
        </div>

        <div className="flex items-center gap-2.5 shrink-0 z-10">
          <select
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value)}
            className="px-3.5 py-2.5 bg-slate-50 hover:bg-slate-100 border border-slate-200 text-slate-800 font-bold rounded-2xl text-xs focus:outline-none"
          >
            <option value="Last 30 Days" className="text-slate-900">Last 30 Days</option>
            <option value="Current Quarter" className="text-slate-900">Current Quarter</option>
            <option value="FY 2025-26" className="text-slate-900">Fiscal Year 2025-26</option>
            <option value="All Time" className="text-slate-900">All Time Cumulative</option>
          </select>

          <button
            onClick={handleExportReport}
            className="flex items-center gap-2 px-5 py-2.5 bg-[#0a2558] hover:bg-[#071c42] text-white font-bold rounded-2xl text-xs shadow-md transition-all transform hover:scale-105"
          >
            <Download className="w-4 h-4 text-blue-200" />
            <span>Export Report</span>
          </button>
        </div>
      </div>

      {/* ─── TOP KPI SUMMARY CARDS ─── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        
        {/* Total Trainees Enrolled */}
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Total Enrolled Cadre</span>
            <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center font-bold">
              <GraduationCap className="w-5 h-5" />
            </div>
          </div>
          <div>
            <p className="text-2xl font-black text-slate-900">{totalEnrolled}</p>
            <p className="text-[11px] text-emerald-600 font-semibold flex items-center gap-1 mt-0.5">
              <TrendingUp className="w-3.5 h-3.5" />
              <span>+18.4% intake this cycle</span>
            </p>
          </div>
        </div>

        {/* Capacity Utilization */}
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Seat Capacity Utilization</span>
            <div className="w-10 h-10 rounded-xl bg-purple-50 text-purple-700 flex items-center justify-center font-bold">
              <Users className="w-5 h-5" />
            </div>
          </div>
          <div>
            <p className="text-2xl font-black text-slate-900">{capacityUtilizationPct}%</p>
            <p className="text-[11px] text-slate-500 font-semibold mt-0.5">
              {totalEnrolled} / {totalMaxCapacity} capacity filled
            </p>
          </div>
        </div>

        {/* First-Attempt Pass Rate */}
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">First-Attempt Pass Rate</span>
            <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center font-bold">
              <CheckCircle2 className="w-5 h-5" />
            </div>
          </div>
          <div>
            <p className="text-2xl font-black text-emerald-600">{stats?.overallPassRate ?? 0}%</p>
            <p className="text-[11px] text-slate-500 font-semibold mt-0.5">
              Passing threshold: 60% standard
            </p>
          </div>
        </div>

        {/* Verified Certificates Issued */}
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Credentials Issued</span>
            <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center font-bold">
              <Award className="w-5 h-5" />
            </div>
          </div>
          <div>
            <p className="text-2xl font-black text-slate-900">{stats?.totalCertificatesIssued ?? 0}</p>
            <p className="text-[11px] text-amber-700 font-semibold mt-0.5 flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>100% Cryptographic MoES Seals</span>
            </p>
          </div>
        </div>

      </div>

      {/* ─── SUB-NAVIGATION TABS ─── */}
      <div className="bg-white rounded-2xl border border-slate-200 p-2 shadow-sm flex flex-wrap items-center gap-2">
        {[
          { id: "capacity", label: "Program Capacity & Enrollments", icon: BookOpen },
          { id: "performance", label: "Assessment & Grade Distributions", icon: BarChart3 },
          { id: "faculty", label: "Faculty Workload & Ratios", icon: Users },
          { id: "compliance", label: "Certification & Compliance Trends", icon: Award }
        ].map(tab => {
          const Icon = tab.icon;
          const isSelected = activeSubTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveSubTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl font-bold text-xs transition-all ${
                isSelected
                  ? "bg-[#0a2558] text-white shadow-sm"
                  : "text-slate-600 hover:bg-slate-100"
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* ─── TAB 1: PROGRAM CAPACITY & ENROLLMENTS ─── */}
      {activeSubTab === "capacity" && (
        <div className="space-y-6">
          
          {/* Capacity Utilization Table / Cards */}
          <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-4 border-b border-slate-100">
              <div>
                <h3 className="text-sm font-black text-slate-900">Operational Program Seat Capacities</h3>
                <p className="text-xs text-slate-500">Live tracker of enrolled officers versus administrative seat limits</p>
              </div>
              <span className="text-xs font-bold text-blue-700 bg-blue-50 px-3 py-1 rounded-xl border border-blue-100">
                {courses.length} Active Tracks
              </span>
            </div>

            <div className="space-y-4">
              {courses.length === 0 ? (
                <div className="p-8 text-center text-slate-400 font-medium text-xs">
                  No operational courses registered in system.
                </div>
              ) : (
                courses.map(course => {
                  const enrolled = course.enrolledTraineeIds?.length || 0;
                  const max = course.maxEnrollment || 50;
                  const pct = Math.round((enrolled / max) * 100);

                  return (
                    <div key={course.id} className="p-4 rounded-2xl bg-slate-50 border border-slate-200/80 space-y-2.5">
                      <div className="flex flex-wrap items-center justify-between gap-2">
                        <div className="flex items-center gap-2.5">
                          <span className="px-2 py-0.5 rounded-md text-[10px] font-bold bg-[#0a2558] text-white">
                            {course.code}
                          </span>
                          <span className="font-bold text-slate-900 text-xs sm:text-sm">{course.title}</span>
                        </div>
                        <div className="flex items-center gap-3 text-xs">
                          <span className="text-slate-500 font-medium">Category: <b className="text-slate-700">{course.category}</b></span>
                          <span className="font-bold text-slate-900 bg-white px-2.5 py-1 rounded-lg border border-slate-200">
                            {enrolled} / {max} Officers ({pct}%)
                          </span>
                        </div>
                      </div>

                      {/* Progress Bar */}
                      <div className="w-full bg-slate-200 h-2.5 rounded-full overflow-hidden">
                        <div
                          className={`h-full transition-all duration-500 rounded-full ${
                            pct >= 90 ? "bg-rose-500" : pct >= 70 ? "bg-blue-600" : "bg-emerald-500"
                          }`}
                          style={{ width: `${Math.min(pct, 100)}%` }}
                        />
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>

          {/* Departmental Participation Breakdown */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
              <h3 className="text-sm font-black text-slate-900 flex items-center gap-2">
                <Building2 className="w-4 h-4 text-blue-600" />
                <span>Departmental Cadre Distribution</span>
              </h3>
              
              <div className="space-y-3 text-xs">
                {(stats?.deptDistribution && stats.deptDistribution.length > 0 ? stats.deptDistribution : []).map((dept, i) => (
                  <div key={i} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-100">
                    <span className="font-semibold text-slate-800">{dept.name}</span>
                    <span className="font-bold text-blue-800 bg-blue-100 px-2.5 py-0.5 rounded-lg">
                      {dept.count} Officers ({dept.activeTrainees || 0} active)
                    </span>
                  </div>
                ))}
                {(!stats?.deptDistribution || stats.deptDistribution.length === 0) && (
                  <div className="p-4 text-center text-slate-400 font-medium text-xs">
                    No departmental distribution data available.
                  </div>
                )}
              </div>
            </div>

            <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
              <h3 className="text-sm font-black text-slate-900 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-600" />
                <span>National Center Participation</span>
              </h3>

              <div className="space-y-3 text-xs">
                {(stats?.centers && stats.centers.length > 0 ? stats.centers : []).map((item, idx) => (
                  <div key={idx} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-100">
                    <div>
                      <p className="font-semibold text-slate-800">{item.center}</p>
                      <p className="text-[10px] text-slate-400">{item.status}</p>
                    </div>
                    <span className="font-bold text-slate-900 text-xs">{item.participants} ({item.count} Officers)</span>
                  </div>
                ))}
                {(!stats?.centers || stats.centers.length === 0) && (
                  <div className="p-4 text-center text-slate-400 font-medium text-xs">
                    No regional station participation records yet.
                  </div>
                )}
              </div>
            </div>

          </div>

        </div>
      )}

      {/* ─── TAB 2: ASSESSMENT & PERFORMANCE DISTRIBUTION ─── */}
      {activeSubTab === "performance" && (
        <div className="space-y-6">
          
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            
            <div className="bg-emerald-50 p-5 rounded-2xl border border-emerald-200 space-y-1">
              <p className="text-[11px] font-bold uppercase text-emerald-800">Distinction (90 - 100%)</p>
              <p className="text-2xl font-black text-emerald-900">{stats?.gradeDistribution?.distinction?.percentage ?? "0.0"}%</p>
              <p className="text-[10px] text-emerald-700">{stats?.gradeDistribution?.distinction?.count ?? 0} Submissions</p>
            </div>

            <div className="bg-blue-50 p-5 rounded-2xl border border-blue-200 space-y-1">
              <p className="text-[11px] font-bold uppercase text-blue-800">First Class (75 - 89%)</p>
              <p className="text-2xl font-black text-blue-900">{stats?.gradeDistribution?.firstClass?.percentage ?? "0.0"}%</p>
              <p className="text-[10px] text-blue-700">{stats?.gradeDistribution?.firstClass?.count ?? 0} Submissions</p>
            </div>

            <div className="bg-amber-50 p-5 rounded-2xl border border-amber-200 space-y-1">
              <p className="text-[11px] font-bold uppercase text-amber-800">Passing Grade (60 - 74%)</p>
              <p className="text-2xl font-black text-amber-900">{stats?.gradeDistribution?.passing?.percentage ?? "0.0"}%</p>
              <p className="text-[10px] text-amber-700">{stats?.gradeDistribution?.passing?.count ?? 0} Submissions</p>
            </div>

            <div className="bg-rose-50 p-5 rounded-2xl border border-rose-200 space-y-1">
              <p className="text-[11px] font-bold uppercase text-rose-800">Remedial Required (&lt;60%)</p>
              <p className="text-2xl font-black text-rose-900">{stats?.gradeDistribution?.remedial?.percentage ?? "0.0"}%</p>
              <p className="text-[10px] text-rose-700">{stats?.gradeDistribution?.remedial?.count ?? 0} Submissions</p>
            </div>

          </div>

          {/* Quizzes and Topic Accuracy Table */}
          <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
            <h3 className="text-sm font-black text-slate-900">Operational Subject Mastery & Evaluation History</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-200 text-slate-400 font-bold uppercase text-[10px]">
                    <th className="pb-3">Assessment Title</th>
                    <th className="pb-3">Course / Subject</th>
                    <th className="pb-3">Duration / Marks</th>
                    <th className="pb-3">Scheduled Time</th>
                    <th className="pb-3">Passing Marks</th>
                    <th className="pb-3 text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {quizzes.length === 0 ? (
                    <tr>
                      <td colSpan="6" className="py-8 text-center text-slate-400 font-medium">
                        No scheduled assessments found in registry.
                      </td>
                    </tr>
                  ) : (
                    quizzes.map((q, idx) => (
                      <tr key={idx} className="hover:bg-slate-50">
                        <td className="py-3 font-bold text-slate-900">{q.title}</td>
                        <td className="py-3 text-slate-600">{q.subject || q.courseTitle || "Atmospheric Dynamics"}</td>
                        <td className="py-3 font-semibold text-slate-800">{q.durationMinutes || 30} mins • {q.totalMarks || 20} Marks</td>
                        <td className="py-3 font-medium text-slate-500">
                          {q.scheduledStartTime ? new Date(q.scheduledStartTime).toLocaleDateString() : "Open Schedule"}
                        </td>
                        <td className="py-3 font-bold text-emerald-700">{q.passMarks || Math.round((q.totalMarks || 20) * 0.6)} Marks</td>
                        <td className="py-3 text-right">
                          <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                            q.status === "Published" || q.resultsPublished ? "bg-blue-100 text-blue-800" : "bg-emerald-100 text-emerald-800"
                          }`}>
                            {q.status || "Active Evaluation"}
                          </span>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      )}

      {/* ─── TAB 3: FACULTY WORKLOAD & RATIOS ─── */}
      {activeSubTab === "faculty" && (
        <div className="space-y-6">
          
          <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100">
              <div>
                <h3 className="text-sm font-black text-slate-900">Faculty Workload Balance Matrix</h3>
                <p className="text-xs text-slate-500">Live operational teaching assignments and student-to-trainer ratios</p>
              </div>
              <span className="text-xs font-bold text-slate-600 bg-slate-100 px-3 py-1 rounded-xl">
                {trainersWorkload.length} Certified Instructors
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {trainersWorkload.map((trainer) => (
                <div key={trainer.trainerId} className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="font-black text-slate-900 text-sm">{trainer.trainerName}</h4>
                      <p className="text-[11px] text-slate-500">{trainer.designation || "Senior Meteorologist"}</p>
                    </div>
                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                      trainer.status === "High Load"
                        ? "bg-rose-100 text-rose-800"
                        : trainer.status === "Optimal"
                        ? "bg-blue-100 text-blue-800"
                        : "bg-emerald-100 text-emerald-800"
                    }`}>
                      {trainer.status}
                    </span>
                  </div>

                  <div className="grid grid-cols-2 gap-2 text-xs bg-white p-3 rounded-xl border border-slate-200/80">
                    <div>
                      <p className="text-slate-400 text-[10px] uppercase font-bold">Active Courses</p>
                      <p className="text-sm font-black text-slate-900">{trainer.activeCoursesCount}</p>
                    </div>
                    <div>
                      <p className="text-slate-400 text-[10px] uppercase font-bold">Subjects Handled</p>
                      <p className="text-sm font-black text-blue-700">{trainer.assignedSubjects?.length || 0}</p>
                    </div>
                  </div>

                  <div className="space-y-1 text-xs">
                    <p className="text-[10px] font-bold text-slate-400 uppercase">Assigned Subjects:</p>
                    <div className="flex flex-wrap gap-1">
                      {(trainer.assignedSubjects || []).map((sub, sIdx) => (
                        <span key={sIdx} className="text-[10px] bg-slate-200 text-slate-700 px-2 py-0.5 rounded font-medium truncate max-w-[150px]">
                          {sub.subjectTitle}
                        </span>
                      ))}
                      {(trainer.assignedSubjects?.length || 0) === 0 && (
                        <span className="text-[10px] text-slate-400 italic">No current subject duties</span>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>
      )}

      {/* ─── TAB 4: CERTIFICATION & COMPLIANCE TRENDS ─── */}
      {activeSubTab === "compliance" && (
        <div className="space-y-6">
          
          <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-4 border-b border-slate-100">
              <div>
                <h3 className="text-sm font-black text-slate-900">Institutional Certification & Compliance Trajectory</h3>
                <p className="text-xs text-slate-500">Historical credential issuance and MoES/WMO standards compliance audit</p>
              </div>
              <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5" /> 100% Audited
              </span>
            </div>

            {/* Monthly Trend Bars */}
            <div className="grid grid-cols-2 sm:grid-cols-6 gap-3 pt-2">
              {(stats?.monthlyCertifications && stats.monthlyCertifications.length > 0 ? stats.monthlyCertifications : []).map((m, i) => (
                <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-200 text-center space-y-2">
                  <span className="text-xs font-bold text-slate-600">{m.month} 2025/26</span>
                  <div className="text-xl font-black text-[#0a2558]">{m.certificates}</div>
                  <p className="text-[10px] text-slate-400 font-semibold">{m.enrollments} Enrolled</p>
                  <div className="w-full bg-slate-200 h-1.5 rounded-full overflow-hidden">
                    <div className="bg-[#0a2558] h-full rounded-full" style={{ width: `${Math.min((m.certificates / (Math.max(1, m.enrollments))) * 100, 100)}%` }} />
                  </div>
                </div>
              ))}
              {(!stats?.monthlyCertifications || stats.monthlyCertifications.length === 0) && (
                <div className="col-span-full p-6 text-center text-slate-400 text-xs font-medium">
                  No monthly certification metrics recorded for selected timeframe.
                </div>
              )}
            </div>
          </div>

          <div className="p-5 rounded-2xl bg-blue-50 border border-blue-200 flex items-start gap-3">
            <ShieldCheck className="w-5 h-5 text-blue-700 shrink-0 mt-0.5" />
            <div className="space-y-1 text-xs text-blue-950">
              <p className="font-bold">National Compliance Guarantee:</p>
              <p className="text-blue-800 leading-relaxed">
                All training modules, quiz evaluations, and digital credentials issued on the Capacity Connect portal strictly adhere to the WMO Guidelines on Meteorological Training & Education (WMO-No. 258) and National Standards of the Ministry of Earth Sciences.
              </p>
            </div>
          </div>

        </div>
      )}

    </div>
  );
};
